CREATE TABLE FUNCIONARIO (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CARGO VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE PACIENTE (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    IDADE INTEGER NOT NULL,
    SEXO VARCHAR(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE PRONTUARIO (
    ID BIGINT(20) PRIMARY KEY,
    ID_FUNCIONARIO BIGINT(20),
    ID_PACIENTE BIGINT(20),
    DATA_ENTRADA DATETIME NOT NULL,
    DATA_SAIDA DATETIME,
    DOENCA VARCHAR(50),
    DIAGNOSTICO VARCHAR(300),
    MEDICACAO VARCHAR(300),
    STATUS VARCHAR(300),
    FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID),
    FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;